export const aiTools = [
  { id: 1, nazwa: "ChatGPT", opis: "Najpotężniejszy uniwersalny AI – pisanie, kod, research, obrazy, voice.", link: "https://chatgpt.com", ikona: "https://chatgpt.com/favicon.ico", kategorie: ["Uniwersalny", "Pisanie", "Kodowanie", "Obrazy"], pricing: "Freemium", najlepsze_do: "Wszystko", popularnosc: 10 },
  { id: 2, nazwa: "Claude", opis: "Najlepszy do długich tekstów, analizy dokumentów i skomplikowanego kodu.", link: "https://claude.ai", ikona: "https://claude.ai/favicon.ico", kategorie: ["Pisanie", "Kodowanie"], pricing: "Freemium", najlepsze_do: "Pisanie książek i analizy", popularnosc: 9 },
  { id: 3, nazwa: "Gemini", opis: "Google AI zintegrowany z Gmail, Docs i wyszukiwaniem na żywo.", link: "https://gemini.google.com", ikona: "https://gemini.google.com/favicon.ico", kategorie: ["Uniwersalny", "Research"], pricing: "Darmowe", najlepsze_do: "Praca z Google", popularnosc: 9 },
  { id: 4, nazwa: "Grok", opis: "Prawdomówny AI od xAI z danymi z X w czasie rzeczywistym.", link: "https://grok.x.ai", ikona: "https://grok.x.ai/favicon.ico", kategorie: ["Uniwersalny", "Research"], pricing: "Freemium", najlepsze_do: "Aktualne wydarzenia i humor", popularnosc: 8 },
  { id: 5, nazwa: "Perplexity", opis: "Najlepszy AI Search Engine z cytowanymi źródłami.", link: "https://www.perplexity.ai", ikona: "https://www.perplexity.ai/favicon.ico", kategorie: ["Research"], pricing: "Freemium", najlepsze_do: "Szybki research", popularnosc: 9 },
  { id: 6, nazwa: "Midjourney", opis: "Najpiękniejsze obrazy artystyczne i projektowe.", link: "https://www.midjourney.com", ikona: "https://www.midjourney.com/favicon.ico", kategorie: ["Obrazy"], pricing: "Płatne", najlepsze_do: "Sztuka i design", popularnosc: 8 },
  { id: 7, nazwa: "Cursor", opis: "VS Code na sterydach – AI pisze cały kod za Ciebie.", link: "https://cursor.com", ikona: "https://cursor.com/favicon.ico", kategorie: ["Kodowanie"], pricing: "Freemium", najlepsze_do: "Programowanie", popularnosc: 9 },
  { id: 8, nazwa: "Poe", opis: "Wszystkie modele w jednym miejscu (Claude, GPT, Gemini, Llama).", link: "https://poe.com", ikona: "https://poe.com/favicon.ico", kategorie: ["Uniwersalny"], pricing: "Freemium", najlepsze_do: "Testowanie modeli", popularnosc: 8 },
  { id: 9, nazwa: "ElevenLabs", opis: "Najlepszy głos AI – klonowanie głosu i synteza.", link: "https://elevenlabs.io", ikona: "https://elevenlabs.io/favicon.ico", kategorie: ["Audio"], pricing: "Freemium", najlepsze_do: "Podcasty i voice-over", popularnosc: 8 },
  { id: 10, nazwa: "Runway", opis: "Generowanie i edycja wideo AI (Gen-3).", link: "https://runwayml.com", ikona: "https://runwayml.com/favicon.ico", kategorie: ["Wideo"], pricing: "Płatne", najlepsze_do: "Wideo kreatywne", popularnosc: 7 }
]
